Update sync-branches.yml

diff --git a/.github/workflows/sync-branches.yml b/.github/workflows/sync-branches.yml
--- a/.github/workflows/sync-branches.yml
+++ b/.github/workflows/sync-branches.yml
@@ -45,9 +45,9 @@ jobs:
           add_or_update_remote dragonpilot https://github.com/dragonpilot/dragonpilot.git
           git fetch dragonpilot pre-build --no-tags || echo "⚠️ dragonpilot pre-build fetch failed"
 
-          # Fishop
-          add_or_update_remote fishop_remote https://jihulab.com/fishop/openpilot.git
-          git fetch fishop_remote cp --no-tags || echo "⚠️ fishop fetch failed"
+          # c3-ms
+          add_or_update_remote c3-ms https://github.com/happymaj11r/openpilot.git
+          git fetch c3-ms c3-ms --no-tags || echo "⚠️ c3-ms fetch failed"
 
       - name: Push branches to your repository (force sync)
         run: |
@@ -77,7 +77,7 @@ jobs:
           sync_branch Carrotpilot carrotpilot/c3-wip
           sync_branch release iqpilot/release-new
           sync_branch Dragonpilot dragonpilot/pre-build
-          sync_branch fishop fishop_remote/cp
+          sync_branch c3-ms c3-ms/c3-ms
 
       - name: Tag sync timestamp
         run: |
